import { Chapter } from '../types'

export const chapters: Chapter[] = [
  {
    id: 1,
    act: 'ACT I — THE ORIGIN',
    actNumber: 1,
    title: 'The First Star',
    subtitle: 'Every universe begins with a single point of light.',
    story: [
      'Before the universe existed, there was only silence. Infinite, patient, waiting.',
      'And then — from somewhere in the dark — one small action. Not a grand declaration. Not fireworks. Just a single moment that rearranged everything.',
      'That\'s how the best stories begin. Quietly. Without warning. In a place where neither person expected to find the other.',
      'This is where yours started. Answer the question below, and step into the first chapter of your universe.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'What mobile game first connected your paths?',
      hint1: 'A multiplayer battle arena game hugely popular in Southeast Asia.',
      hint2: 'The acronym is 4 letters: M · L · B · B',
      hint3: 'Mobile Legends: Bang Bang',
      answers: ['mlbb', 'mobile legends', 'mobile legends bang bang', 'mobile legends: bang bang'],
    },
    bg: '/assets/backgrounds/galaxy-01.webp',
    themeClass: 'act-1',
    successMessage: 'The first star ignites.',
  },
  {
    id: 2,
    act: 'ACT I — THE ORIGIN',
    actNumber: 1,
    title: 'The Follow',
    subtitle: 'It started so simply. Not with words — with one tap.',
    story: [
      'She followed him. That was it.',
      'One notification. One small digital gesture among thousands happening every second across the world. And yet this one was different.',
      'Because on the other side of that follow was a person. A real, curious, wondering person. And something about it made him pay attention.',
      'The universe has a way of using the most ordinary moments to start the most extraordinary things.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'What single action started everything between you?',
      hint1: 'The simplest gesture on any social or gaming platform.',
      hint2: 'Not a like. Not a comment. Not a message. Just one tap.',
      hint3: 'She followed him — 6 letters.',
      answers: ['follow', 'a follow', 'one follow', 'she followed', 'followed'],
    },
    bg: '/assets/backgrounds/galaxy-01.webp',
    themeClass: 'act-1',
    successMessage: 'The constellation stirs.',
  },
  {
    id: 3,
    act: 'ACT I — THE ORIGIN',
    actNumber: 1,
    title: 'First Conversations',
    subtitle: 'Two strangers waiting for the same green dot.',
    story: [
      'He noticed. She noticed. And then came the waiting.',
      'Checking if she was online. Keeping the app open a little longer than usual. Wondering if she\'d reply — and feeling something when she did.',
      'That\'s the tell, isn\'t it? When someone becomes the reason you check your phone. When a notification from one specific person feels different from all the others.',
      'Curiosity. That warm, restless, searching kind. It had already begun.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'What were you both waiting for each other to be?',
      hint1: 'You\'d check for a little green indicator.',
      hint2: 'The opposite of offline.',
      hint3: 'You kept looking to see if she was... online.',
      answers: ['online', 'go online', 'come online', 'be online'],
    },
    bg: '/assets/backgrounds/galaxy-01.webp',
    themeClass: 'act-1',
    successMessage: 'A signal travels through the dark.',
  },
  {
    id: 4,
    act: 'ACT I — THE ORIGIN',
    actNumber: 1,
    title: 'Instagram',
    subtitle: 'One galaxy wasn\'t enough to contain what was growing.',
    story: [
      'The game was too small for this.',
      'What had started in the corridors of MLBB needed more space — more ways to exist, more ways to know each other. And so they moved.',
      'A new platform. More pictures. More stories. More reasons to keep the conversation going.',
      'Every photo glimpsed. Every post. Every reply. All of it slowly, piece by piece, building something that didn\'t have a name yet.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'Which platform did your story move to next?',
      hint1: 'A photo and video sharing app with Stories and Reels.',
      hint2: 'Two letters if you use the short version: I and G.',
      hint3: 'Where hearts meet square photos — Instagram.',
      answers: ['instagram', 'ig', 'insta', 'instagram dm'],
    },
    bg: '/assets/backgrounds/galaxy-01.webp',
    themeClass: 'act-1',
    successMessage: 'A new world opens.',
  },
  {
    id: 5,
    act: 'ACT I — THE ORIGIN',
    actNumber: 1,
    title: 'The Hidden Identity',
    subtitle: 'A mystery behind a screen. Beautiful and guarded.',
    story: [
      'She wasn\'t ready to be known. Not yet.',
      'So she wore a different name. Not out of deception — out of that very human need to protect yourself until you know it\'s safe to be seen.',
      'And he was curious. Not frustrated. Curious. He wanted to know who was really on the other side.',
      'The mystery only made him want to stay.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'What name did she use before her true identity was revealed?',
      hint1: 'Four letters. A name that wasn\'t her real name.',
      hint2: 'Before Alinah Joyce, she introduced herself as someone else...',
      hint3: 'The temporary name she hid behind was: Ella.',
      answers: ['ella'],
    },
    bg: '/assets/backgrounds/nebula-blue.jpg',
    themeClass: 'act-1',
    successMessage: 'The veil begins to lift.',
  },
  {
    id: 6,
    act: 'ACT II — DISCOVERY',
    actNumber: 2,
    title: 'The Search',
    subtitle: 'She disappeared. And something in him couldn\'t just move on.',
    story: [
      'She was gone.',
      'No goodbye. No warning. Just gone. And he felt something he didn\'t expect — not just curiosity, but worry. The kind that sits in your chest and doesn\'t move.',
      'Something in the news made it worse. A force of nature had passed through. And all he could think about was: Is she okay? Are they safe?',
      'So he started looking. Not because he had to. Because he cared.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'What natural event worried him and drove him to search for her?',
      hint1: 'A weather phenomenon common in the Philippines.',
      hint2: 'In Filipino, it\'s called "bagyo."',
      hint3: 'Strong winds, heavy rain — a typhoon.',
      answers: ['typhoon', 'storm', 'bagyo', 'the typhoon', 'a typhoon', 'a storm'],
    },
    bg: '/assets/backgrounds/nebula-blue.jpg',
    themeClass: 'act-2',
    successMessage: 'The search begins.',
  },
  {
    id: 7,
    act: 'ACT II — DISCOVERY',
    actNumber: 2,
    title: 'Francisco?',
    subtitle: 'He became a detective of hearts — following clues through the universe.',
    story: [
      'He searched. Methodically. Carefully. Like someone who needed to know.',
      'And then — a clue. A surname surfacing from the quiet corners of the internet. A name that felt like it could be her.',
      '"Francisco ba last name mo?"',
      'He even sent a photo. Confident. Maybe a little nervous. But moving forward anyway.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'What surname did he discover during his search?',
      hint1: 'A Spanish-origin Filipino surname.',
      hint2: 'Nine letters. It starts with F.',
      hint3: 'Francisco — the name he found while looking for her.',
      answers: ['francisco'],
    },
    bg: '/assets/backgrounds/nebula-blue.jpg',
    themeClass: 'act-2',
    successMessage: 'A name emerges from the stars.',
  },
  {
    id: 8,
    act: 'ACT II — DISCOVERY',
    actNumber: 2,
    title: 'Joyce',
    subtitle: 'One name led to another. And another.',
    story: [
      'Behind Francisco was another name. A softer one.',
      'Joyce.',
      'And behind Joyce was the beginning of the whole truth: Alinah Joyce V. Francisco.',
      'With each name discovered, she became more real. More her. No longer a mystery behind a screen — but a person. A specific, beautiful, full person. And he remembered every letter of it.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'What is her second name — the name between Alinah and Francisco?',
      hint1: 'A beautiful five-letter English name.',
      hint2: 'It rhymes with "voice."',
      hint3: 'Alinah ___ V. Francisco — Joyce.',
      answers: ['joyce', 'alinah joyce'],
    },
    bg: '/assets/backgrounds/nebula-blue.jpg',
    themeClass: 'act-2',
    successMessage: 'Her name glows in the constellation.',
  },
  {
    id: 9,
    act: 'ACT II — DISCOVERY',
    actNumber: 2,
    title: 'The Wrong Photo',
    subtitle: 'So close. But the universe had one more test.',
    story: [
      'He was getting closer. He could feel it.',
      'He found a photo. Sent it. Confident. "Is this you?"',
      'It was not her.',
      'It was her cousin. And she was not amused. She had her tampuhan moment — and somehow, in her reaction, she became even more real to him. Even more hers. He explained. He apologized. He kept going. Because giving up was never the plan.',
    ],
    puzzle: {
      type: 'choice',
      prompt: 'Whose photo did he accidentally send, thinking it was her?',
      options: [
        { id: 'a', label: 'Her sister' },
        { id: 'b', label: 'Her cousin (pinsan)' },
        { id: 'c', label: 'A random stranger' },
        { id: 'd', label: 'Her best friend' },
      ],
      hint1: 'It was someone related to her.',
      hint2: 'Not a sibling — a different kind of family member.',
      hint3: 'In Filipino: pinsan — her cousin.',
      answers: ['b', 'her cousin', 'cousin', 'pinsan'],
    },
    bg: '/assets/backgrounds/nebula-blue.jpg',
    themeClass: 'act-2',
    successMessage: 'Closer now. So much closer.',
  },
  {
    id: 10,
    act: 'ACT II — DISCOVERY',
    actNumber: 2,
    title: 'The Crush',
    subtitle: 'Truth or Dare. The universe\'s favorite revealer.',
    story: [
      'They played a game. A classic one.',
      'And somewhere in the middle of it, the truth came out — that they had feelings for each other. Mutual. Both of them. At the same time.',
      'And he said he wouldn\'t go to her wedding someday.',
      'Not because he didn\'t care — because he wanted to be the one standing at the altar with her.',
      '🥲❤️',
    ],
    puzzle: {
      type: 'text',
      prompt: 'What classic game finally revealed your mutual feelings?',
      hint1: 'A game of confessions and choices.',
      hint2: 'Three words. The middle one is "or."',
      hint3: 'Truth ___ Dare.',
      answers: ['truth or dare', 'truth or dare game'],
    },
    bg: '/assets/backgrounds/nebula-blue.jpg',
    themeClass: 'act-2',
    successMessage: 'The stars finally align.',
  },
  {
    id: 11,
    act: 'ACT III — OUR UNIVERSE',
    actNumber: 3,
    title: 'Favorite Things',
    subtitle: 'Learning someone\'s universe, one favorite at a time.',
    story: [
      'Now that they had found each other, it was time to truly know each other.',
      'Her favorite songs — the ones that lived in her chest. Her favorite foods — the ones that felt like home. Her family stories, her habits, her places, her fears, her dreams.',
      'And he listened. To all of it. Slowly. Carefully. Like every detail was worth remembering.',
      'Because it was.',
    ],
    puzzle: {
      type: 'choice',
      prompt: 'What did getting to know each other really mean?',
      options: [
        { id: 'a', label: 'Favorite songs and playlists' },
        { id: 'b', label: 'Favorite foods and comfort meals' },
        { id: 'c', label: 'Family stories and dreams' },
        { id: 'd', label: 'All of these — and so much more' },
      ],
      hint1: 'Think about everything shared in those early conversations.',
      hint2: 'It wasn\'t just one thing — it was many.',
      hint3: 'Answer: All of the above.',
      answers: ['d', 'all', 'all of these', 'all of the above', 'everything'],
    },
    bg: '/assets/backgrounds/orion.jpg',
    themeClass: 'act-3',
    successMessage: 'A world takes shape between you.',
  },
  {
    id: 12,
    act: 'ACT III — OUR UNIVERSE',
    actNumber: 3,
    title: 'MLBB Duo',
    subtitle: 'Back to where it started — but this time, together.',
    story: [
      'They returned to the game where it all began.',
      'But this time, they weren\'t just two separate players who happened to follow each other. They were a team. A duo.',
      'In the same game where a single follow changed everything, they now played side by side. Strategy, laughter, probably some frustration — but together.',
      'The place that started the story became part of the story itself.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'In MLBB, what do you call two players who team up and play together?',
      hint1: 'It\'s a word for two people working as a unit.',
      hint2: 'Not a squad (that\'s 5). Not a trio (that\'s 3).',
      hint3: 'Two people, one team — a duo.',
      answers: ['duo', 'a duo', 'mlbb duo', 'team', 'partners'],
    },
    bg: '/assets/backgrounds/orion.jpg',
    themeClass: 'act-3',
    successMessage: 'Together in the same universe.',
  },
  {
    id: 13,
    act: 'ACT III — OUR UNIVERSE',
    actNumber: 3,
    title: 'Late-Night Talks',
    subtitle: 'The things you say at 2 AM are the things you mean the most.',
    story: [
      'The conversations stretched past midnight.',
      'Tawanan. Iyakan. Lambingan. Random topics that turned into important ones. Silly moments that turned into the kind of memories you hold on to.',
      'Those late-night talks are sacred. The kind that happen when the world is quiet and it\'s just two people being honest with each other.',
      'Those were theirs.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'Complete this Filipino word for "laughing together" — it filled your late-night talks: t-a-w-a-___',
      hint1: 'It ends with "nan." Seven letters total.',
      hint2: 't - a - w - a - n - a - n',
      hint3: 'Tawanan — the sound of two people laughing together.',
      answers: ['tawanan', 'nan', 'laughter', 'laughing', 'tawa'],
    },
    bg: '/assets/backgrounds/orion.jpg',
    themeClass: 'act-3',
    successMessage: 'Laughter echoes through the stars.',
  },
  {
    id: 14,
    act: 'ACT III — OUR UNIVERSE',
    actNumber: 3,
    title: 'Birthdays & New Year',
    subtitle: 'Ordinary dates became marked with meaning — because of you.',
    story: [
      'Time passed. The calendar kept moving.',
      'Birthdays arrived. New Year was counted down together, even across the distance. What were once just dates became something else entirely.',
      'They became anchors. Proof that time was passing and they were still here, still in each other\'s lives.',
      'Still choosing each other, even as the world kept turning.',
    ],
    puzzle: {
      type: 'choice',
      prompt: 'Which of these special occasions did you share together across the distance?',
      options: [
        { id: 'a', label: 'New Year celebrations' },
        { id: 'b', label: 'Birthdays' },
        { id: 'c', label: 'Both of these' },
        { id: 'd', label: 'Neither — you only met recently' },
      ],
      hint1: 'Think about the memories mentioned in your story.',
      hint2: 'There were multiple celebrations. More than one.',
      hint3: 'Birthdays AND New Year — both.',
      answers: ['c', 'both', 'both of these', 'birthdays and new year', 'new year and birthdays'],
    },
    bg: '/assets/backgrounds/orion.jpg',
    themeClass: 'act-3',
    successMessage: 'Time is marked. You were there for all of it.',
  },
  {
    id: 15,
    act: 'ACT III — OUR UNIVERSE',
    actNumber: 3,
    title: 'The Hard Days',
    subtitle: 'Not everything was easy. And they stayed anyway.',
    story: [
      'There were storms that had nothing to do with the weather.',
      'Misunderstandings that carved quiet bruises. Moments when the weight of everything felt too heavy. Moments when the comfort offered wasn\'t enough — and he knew it, and was sorry for it.',
      'But hard days also reveal what something is truly made of.',
      'And what they had? It kept surviving them.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'What medical event did he go through during your relationship?',
      hint1: 'Something that required healing and recovery time.',
      hint2: 'More serious than a regular checkup or illness.',
      hint3: 'He went through surgery.',
      answers: ['surgery', 'operation', 'a surgery', 'an operation'],
    },
    bg: '/assets/backgrounds/orion.jpg',
    themeClass: 'act-3',
    successMessage: 'Through the dark — still here.',
  },
  {
    id: 16,
    act: 'ACT IV — TWO WORLDS',
    actNumber: 4,
    title: 'Distance',
    subtitle: 'Two separate stars. One unwavering pull between them.',
    story: [
      'Two worlds. Two separate points in the vast universe.',
      'An ocean of kilometers between them. And yet — somehow — they found each other every single day.',
      'Distance is a strange thing. It aches. It makes your arms feel too empty. It makes silence feel louder.',
      'But it also proves something. That even across all that space, the connection was real enough to survive.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'What is the greatest physical challenge of a long-distance relationship?',
      hint1: 'The thing that separates you geographically.',
      hint2: 'In Filipino: layo.',
      hint3: 'What LDR stands for is built on this — Distance.',
      answers: ['distance', 'layo', 'kalayo', 'the distance', 'far away', 'being far'],
    },
    bg: '/assets/backgrounds/filament.png',
    themeClass: 'act-4',
    successMessage: 'Even stars separated by light-years still see each other.',
  },
  {
    id: 17,
    act: 'ACT IV — TWO WORLDS',
    actNumber: 4,
    title: 'Difficult Days',
    subtitle: 'A message is hidden in the stars. Decode what they always chose.',
    story: [
      'There were days when the distance felt impossible. When words typed on a screen weren\'t enough, and presence was the only thing that could truly help.',
      'But they learned. Slowly, imperfectly, genuinely — how to be there for each other even from far away.',
      'Even on the most difficult days, there was something they kept choosing.',
      'The message below is encoded. Decode it — and you\'ll find the word that kept them together.',
    ],
    puzzle: {
      type: 'cipher',
      prompt: 'Decode this message using A=1, B=2, C=3 … Z=26:',
      cipher: '19  —  20  —  1  —  25',
      cipherKey: 'Each number = a letter position in the alphabet.',
      hint1: 'Use the alphabet: A=1, B=2, C=3... and so on.',
      hint2: '19=S, 20=T, 1=A, 25=Y',
      hint3: 'The word is STAY.',
      answers: ['stay'],
    },
    bg: '/assets/backgrounds/filament.png',
    themeClass: 'act-4',
    successMessage: 'And they stayed.',
  },
  {
    id: 18,
    act: 'ACT IV — TWO WORLDS',
    actNumber: 4,
    title: 'Choosing Each Other',
    subtitle: 'Arguments. Forgiveness. Coming back. Again and again.',
    story: [
      'They argued. Of course they did.',
      'Words came out wrong sometimes. Silence hurt more than it should have. There was tampuhan, and misunderstanding, and moments when the distance felt personal.',
      'But after every storm, without fail, there was a moment of choosing. To go back. To fix it. To try to understand.',
      'That choice — made again and again — is not weakness. It\'s the foundation of everything.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'After every argument, what did you always choose to do?',
      hint1: 'The opposite of giving up.',
      hint2: 'It involves honesty and words and effort.',
      hint3: 'To communicate. To fix it. To stay.',
      answers: [
        'communicate', 'talk', 'stay', 'bati', 'magbati',
        'forgive', 'make up', 'fix it', 'come back', 'understand',
        'choose each other', 'choose to stay',
      ],
    },
    bg: '/assets/backgrounds/filament.png',
    themeClass: 'act-4',
    successMessage: 'The stars remember every time you chose to stay.',
  },
  {
    id: 19,
    act: 'ACT IV — TWO WORLDS',
    actNumber: 4,
    title: 'College',
    subtitle: 'A new chapter of life. A new chapter of us.',
    story: [
      'A new universe arrived. Louder. Heavier. More demanding.',
      'Deadlines, professors, responsibilities that pressed from every direction. A whole new system to navigate while still holding everything else together.',
      'College was its own planet. And they had to learn to move through it — separately but connected, growing as individuals while growing together.',
      'The beginning of something entirely new.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'What new chapter of life did you both begin together?',
      hint1: 'A new academic journey after senior high.',
      hint2: 'After high school comes...',
      hint3: 'College — the new chapter.',
      answers: ['college', 'university', 'uni', 'school', 'college life'],
    },
    bg: '/assets/backgrounds/filament.png',
    themeClass: 'act-4',
    successMessage: 'A new star is born.',
  },
  {
    id: 20,
    act: 'ACT V — OUR NEXT CHAPTER',
    actNumber: 5,
    title: 'Keep Going',
    subtitle: 'One day at a time. One step at a time.',
    story: [
      'Some days felt impossibly heavy.',
      'Pagod na pagod. Gusto na sumuko. The kind of tired that goes beyond physical — the kind that reaches your soul.',
      'But they kept going. Not because it was easy. Not because they had it all figured out. But because quitting was never really the plan.',
      'When everything feels too heavy, one step is enough. Just one more step.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'What essential skill do you need most to balance college, life, and your relationship?',
      hint1: 'Every student struggles with this.',
      hint2: 'Two words — the second one is "management."',
      hint3: 'Time management — learning to balance it all.',
      answers: [
        'time management', 'timemanagement', 'managing time',
        'balance', 'time', 'discipline',
      ],
    },
    bg: '/assets/backgrounds/pillars.png',
    themeClass: 'act-5',
    successMessage: 'One more step. You\'re still moving.',
  },
  {
    id: 21,
    act: 'ACT V — OUR NEXT CHAPTER',
    actNumber: 5,
    title: 'Our Future',
    subtitle: 'Not everything is figured out. And that\'s okay.',
    story: [
      'Beyond all the hard days — there is something waiting.',
      'Dreams they each carry. Versions of themselves they\'re still becoming. A life that exists on the other side of all the exams and deadlines and distance.',
      'They don\'t have to have it all figured out right now. The only requirement is to keep choosing each other while they grow — as partners, as best friends, as two people becoming better versions of themselves.',
      'The future is not something that happens to them. It\'s something they\'re building together.',
    ],
    puzzle: {
      type: 'text',
      prompt: 'What is the most beautiful thing two people can build, one day at a time?',
      hint1: 'It\'s not a house or a building — it\'s something more lasting.',
      hint2: 'It belongs to both of you. It\'s made of time and choice.',
      hint3: 'A future. Together.',
      answers: [
        'future', 'a future', 'our future', 'together', 'love',
        'memories', 'dreams', 'us', 'life', 'a life together',
      ],
    },
    bg: '/assets/backgrounds/pillars.png',
    themeClass: 'act-5',
    successMessage: 'The future is already taking shape.',
  },
  {
    id: 22,
    act: 'ACT V — OUR NEXT CHAPTER',
    actNumber: 5,
    title: 'The Last Star',
    subtitle: 'Twenty-two moments. Twenty-two memories. One final constellation.',
    story: [
      'You\'ve traveled through 22 chapters. 22 moments that make up the story of you.',
      'Now, they all come together into one constellation. The map of everything you\'ve been through.',
      'Light up every star — all 22 of them. Let the constellation remember.',
      'Then speak the word that lives at the heart of all of it.',
    ],
    puzzle: {
      type: 'constellation',
      prompt: 'Light all 22 stars, then speak the word at the heart of your story.',
      starCount: 22,
      hint1: 'Click every star in the constellation to light them up.',
      hint2: 'The word is a term of endearment used in the letter.',
      hint3: 'The word is: palangga.',
      answers: ['palangga', 'langga', 'mahal kita', 'i love you', 'forever', 'us'],
    },
    bg: '/assets/backgrounds/deep-space.png',
    themeClass: 'act-5',
    successMessage: 'The constellation is complete. The final star is waiting.',
  },
  {
    id: 23,
    act: 'ACT V — OUR NEXT CHAPTER',
    actNumber: 5,
    title: 'For You',
    subtitle: '23 · 08 · 2026',
    story: [],
    bg: '/assets/backgrounds/deep-space.png',
    themeClass: 'act-5',
    successMessage: '',
  },
]

export const getChapter = (id: number): Chapter | undefined =>
  chapters.find(c => c.id === id)
